version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-compose
    ports:
      - "8000:8000"
    command:
    - /bin/bash
    - -c
    - |
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput --clear
      python -m coverage run --source='./savings' manage.py test savings
      python -m coverage report
      python manage.py runserver 0.0.0.0:8000
