version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command:
    - /bin/bash
    - -c
    - |
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput --clear
      python -m coverage run --source='./savings' manage.py test savings
      python -m coverage report
      python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgis/postgis:14-master
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: piggybank
      POSTGRES_DB: piggybank
      POSTGRES_PASSWORD: piggybank
volumes:
  pgdata:
