# Generated by Django 4.1.3 on 2022-11-09 23:07

from django.db import migrations, models
import savings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PiggyBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cent_fifty', savings.models.PositiveIntegerValidatorField(blank=True, default=0, verbose_name='fifty cents')),
                ('cent_five', savings.models.PositiveIntegerValidatorField(blank=True, default=0, verbose_name='five cents')),
                ('cent_one', savings.models.PositiveIntegerValidatorField(blank=True, default=0, verbose_name='one cent')),
                ('cent_ten', savings.models.PositiveIntegerValidatorField(blank=True, default=0, verbose_name='ten cents')),
                ('cent_twenty', savings.models.PositiveIntegerValidatorField(blank=True, default=0, verbose_name='twenty cents')),
                ('cent_two', savings.models.PositiveIntegerValidatorField(blank=True, default=0, verbose_name='two cents')),
                ('euro_fifty', savings.models.PositiveIntegerValidatorField(blank=True, default=0, verbose_name='fifty euros')),
                ('euro_five', savings.models.PositiveIntegerValidatorField(blank=True, default=0, verbose_name='five euros')),
                ('euro_five_hundred', savings.models.PositiveIntegerValidatorField(blank=True, default=0, verbose_name='five hundred euros')),
                ('euro_one', savings.models.PositiveIntegerValidatorField(blank=True, default=0, verbose_name='one euro')),
                ('euro_ten', savings.models.PositiveIntegerValidatorField(blank=True, default=0, verbose_name='ten euros')),
                ('euro_twenty', savings.models.PositiveIntegerValidatorField(blank=True, default=0, verbose_name='twenty euros')),
                ('euro_two', savings.models.PositiveIntegerValidatorField(blank=True, default=0, verbose_name='two euros')),
                ('euro_two_hundred', savings.models.PositiveIntegerValidatorField(blank=True, default=0, verbose_name='two hundred euros')),
                ('euro_one_hundred', savings.models.PositiveIntegerValidatorField(blank=True, default=0, verbose_name='one hundred euros')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Piggy bank',
                'verbose_name_plural': 'Piggy bank',
            },
        ),
    ]
