# Generated by Django 4.1.3 on 2022-11-07 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_remove_piggybank_savings_piggybank_cent_fifty_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='piggybank',
            options={'verbose_name': 'Piggy bank', 'verbose_name_plural': 'Piggy bank'},
        ),
        migrations.RemoveField(
            model_name='piggybank',
            name='euro_hundred',
        ),
        migrations.AddField(
            model_name='piggybank',
            name='euro_one_hundred',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='one hundred euro'),
        ),
        migrations.AlterField(
            model_name='piggybank',
            name='cent_fifty',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='fifty cent'),
        ),
        migrations.AlterField(
            model_name='piggybank',
            name='cent_five',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='five cent'),
        ),
        migrations.AlterField(
            model_name='piggybank',
            name='cent_one',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='one cent'),
        ),
        migrations.AlterField(
            model_name='piggybank',
            name='cent_ten',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ten cent'),
        ),
        migrations.AlterField(
            model_name='piggybank',
            name='cent_twenty',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='twenty cent'),
        ),
        migrations.AlterField(
            model_name='piggybank',
            name='cent_two',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='two cent'),
        ),
        migrations.AlterField(
            model_name='piggybank',
            name='euro_fifty',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='fifty euro'),
        ),
        migrations.AlterField(
            model_name='piggybank',
            name='euro_five',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='five euro'),
        ),
        migrations.AlterField(
            model_name='piggybank',
            name='euro_five_hundred',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='five hundred euro'),
        ),
        migrations.AlterField(
            model_name='piggybank',
            name='euro_one',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='one euro'),
        ),
        migrations.AlterField(
            model_name='piggybank',
            name='euro_ten',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ten euro'),
        ),
        migrations.AlterField(
            model_name='piggybank',
            name='euro_twenty',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='twenty euro'),
        ),
        migrations.AlterField(
            model_name='piggybank',
            name='euro_two',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='two euro'),
        ),
        migrations.AlterField(
            model_name='piggybank',
            name='euro_two_hundred',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='two hundred euro'),
        ),
        migrations.AlterField(
            model_name='piggybank',
            name='total_savings',
            field=models.PositiveIntegerField(default=0, verbose_name=''),
        ),
    ]
