# Generated by Django 4.1.3 on 2022-11-09 22:52

from django.db import migrations
import savings.models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_alter_piggybank_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piggybank',
            name='total_savings',
        ),
        migrations.AlterField(
            model_name='piggybank',
            name='cent_fifty',
            field=savings.models.PositiveIntegerValidatorField(blank=True, default=0, verbose_name='fifty cents'),
        ),
        migrations.AlterField(
            model_name='piggybank',
            name='cent_five',
            field=savings.models.PositiveIntegerValidatorField(blank=True, default=0, verbose_name='five cents'),
        ),
        migrations.AlterField(
            model_name='piggybank',
            name='cent_one',
            field=savings.models.PositiveIntegerValidatorField(blank=True, default=0, verbose_name='one cent'),
        ),
        migrations.AlterField(
            model_name='piggybank',
            name='cent_ten',
            field=savings.models.PositiveIntegerValidatorField(blank=True, default=0, verbose_name='ten cents'),
        ),
        migrations.AlterField(
            model_name='piggybank',
            name='cent_twenty',
            field=savings.models.PositiveIntegerValidatorField(blank=True, default=0, verbose_name='twenty cents'),
        ),
        migrations.AlterField(
            model_name='piggybank',
            name='cent_two',
            field=savings.models.PositiveIntegerValidatorField(blank=True, default=0, verbose_name='two cents'),
        ),
        migrations.AlterField(
            model_name='piggybank',
            name='euro_fifty',
            field=savings.models.PositiveIntegerValidatorField(blank=True, default=0, verbose_name='fifty euros'),
        ),
        migrations.AlterField(
            model_name='piggybank',
            name='euro_five',
            field=savings.models.PositiveIntegerValidatorField(blank=True, default=0, verbose_name='five euros'),
        ),
        migrations.AlterField(
            model_name='piggybank',
            name='euro_five_hundred',
            field=savings.models.PositiveIntegerValidatorField(blank=True, default=0, verbose_name='five hundred euros'),
        ),
        migrations.AlterField(
            model_name='piggybank',
            name='euro_one',
            field=savings.models.PositiveIntegerValidatorField(blank=True, default=0, verbose_name='one euro'),
        ),
        migrations.AlterField(
            model_name='piggybank',
            name='euro_one_hundred',
            field=savings.models.PositiveIntegerValidatorField(blank=True, default=0, verbose_name='one hundred euros'),
        ),
        migrations.AlterField(
            model_name='piggybank',
            name='euro_ten',
            field=savings.models.PositiveIntegerValidatorField(blank=True, default=0, verbose_name='ten euros'),
        ),
        migrations.AlterField(
            model_name='piggybank',
            name='euro_twenty',
            field=savings.models.PositiveIntegerValidatorField(blank=True, default=0, verbose_name='twenty euros'),
        ),
        migrations.AlterField(
            model_name='piggybank',
            name='euro_two',
            field=savings.models.PositiveIntegerValidatorField(blank=True, default=0, verbose_name='two euros'),
        ),
        migrations.AlterField(
            model_name='piggybank',
            name='euro_two_hundred',
            field=savings.models.PositiveIntegerValidatorField(blank=True, default=0, verbose_name='two hundred euros'),
        ),
    ]
